[package]
name = "serde_derive_tests_no_std"
version = "0.0.0"
publish = false

[dependencies]
serde = { path = "../../serde", default-features = false }
serde_derive = { path = "../../serde_derive" }
libc = "*"